### ISSUE TITLE
Cannot load plugin

### ISSUE THREAD

**Issue by kenyroj** [LeeSanghoon/WebSequenceDiagramsForEclipse#1]
Hi

I got this issue and have this message
Plug-in kr.pe.silent.websequencediagrams was unable to load class kr.pe.silent.websequencediagrams.editors.WSDEditor.

I download the WebSequenceDiagramsForEclipse-master.zip and unzip this to eclipse/plugins folder like following
E:\EclipseCPP\plugins\WebSequenceDiagramsForEclipse-master

Do I do something wrong?

Thanks!

**Comment by LeeSanghoon** [comment]
You downloaded a source not a binary.
Try download this : https://ewsd.googlecode.com/files/kr.pe.silent.websequencediagrams_1.0.2.201401151040.jar

And copy to your plugins folder. It will be like this:
`E:\EclipseCPP\plugins\kr.pe.silent.websequencediagrams_1.0.2.201401151040.jar`

**Comment by kenyroj** [comment]
Hi

Thanks for your reply, But I cannot open with following message

java.lang.ClassCastException: org.eclipse.ui.ide.FileStoreEditorInput cannot be cast to org.eclipse.ui.part.FileEditorInput
    at kr.pe.silent.websequencediagrams.editors.WSDEditor.updateImage(WSDEditor.java:115)
    at kr.pe.silent.websequencediagrams.editors.WSDEditor.createPartControl(WSDEditor.java:92)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:141)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:327)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)

Pkease help check, thanks!

**Comment by LeeSanghoon** [comment]
What is your Eclipse version?

I've tried with Eclipse luna, everything is OK.

**Comment by kenyroj** [comment]
Eclipse IDE for C/C++ Developers

Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

Is C++ developers version wrong?
I will try other version in these days.
Thanks

**Comment by kenyroj** [comment]
Hi

I use the following version and get the same error. I give you the screenshot.

Eclipse IDE for Java Developers

Version: Mars Release (4.5.0)
Build id: 20150621-1200

screenshot URL: https://dl.dropboxusercontent.com/u/10482427/WSD.png

Thanks
